<?php
/**
 * PositionItemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MehrIt\OttoOrdersApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Orders
 *
 * This API documentation describes all endpoints for orders - version 3
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace MehrIt\OttoOrdersApiClient;

use MehrIt\OttoOrdersApiClient\Configuration;
use MehrIt\OttoOrdersApiClient\ApiException;
use MehrIt\OttoOrdersApiClient\ObjectSerializer;

/**
 * PositionItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MehrIt\OttoOrdersApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PositionItemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelPartnerOrderPositionItems
     *
     * Cancels PositionItems of an order by ids.
     *
     */
    public function testCancelPartnerOrderPositionItems()
    {
    }
}
